### ISSUE TITLE
Feature request: Max/Min high pulse width, Max/Min low pulse width

### ISSUE THREAD

**Issue by xixixihaha** [saleae/clock-statistics-measurement#1]
This is a feature request, Is it possible to do statistics of Max/Min high pulse with and Max/Min low pulse width in the selected time range?

Thanks!

**Comment by timreyes** [comment]
@xixixihaha It looks like this is possible via a community-shared extension below, which can be installed from within the app.
https://github.com/GrandFatherADI/PulseStats

Here is an image of the extension found within the app.
![Screenshot 2024-10-07 at 1 39 55 PM](https://github.com/user-attachments/assets/6a4dbe04-1635-4bbd-a480-4e6a46419125)

Installation instructions for community-made extensions can be found below as well.
https://support.saleae.com/extensions/installing-extensions

I'll go ahead and close this Issue post for now, however, if you have any questions, feel free to reach out to the original developer, or let us know if you have any general questions about our software via our contact link below.
https://contact.saleae.com/hc/en-us/requests/new

I hope that helps!

**Comment by xixixihaha** [comment]
@timreyes I know there is other extension but have an all-in-one function extension is more convenient. I modified the code and tested fine. I can commit the code if you need it.
<img width="473" alt="image" src="https://github.com/user-attachments/assets/ef58f033-4baf-4be5-84e6-6f6471e65da1">

**Comment by timreyes** [comment]
@xixixihaha Ah understood. Thanks for adding that functionality, and I'm glad you were able to get it working on your end!

Feel free to submit your changes as either a (1) Pull Request, (2) a repository Fork, or (3) both. Our entire software team is prioritizing other projects at the moment, and therefore, we are unable to review your code for official merging in the near term, however, it would be great to get your work posted in the meantime via either or both methods above.
