### ISSUE TITLE
Feature Request: Locate the position of Max/Min values in the waveform

### ISSUE THREAD

**Issue by xixixihaha** [saleae/clock-statistics-measurement#2]
Is it possible to offer the capability to quick locate the max / min values in the captured waveform? Thanks

**Comment by timreyes** [comment]
@xixixihaha This is not possible with our current API implementation for measurement extensions. However, we are currently tracking this feature request below.
https://ideas.saleae.com/b/feature-requests/search-and-highlight-measurements/

I'll add a comment for you in the idea post above to track your need for this and will close this request here in GitHub for now. Thanks for sharing your request!
